#HackRF IQ Analyzer window settings
#Wed Jul 15 00:32:01 CEST 2026
view.burst=false
view.envelope=true
split.divider=491
window.y=4
window.x=-1
audio.volume=51
trigger.enabled=false
window.height=693
view.autoLevel=false
trigger.level=64
audio.toneCutoffHz=16000
audio.enabled=true
trigger.prePercent=25
view.deviation=false
window.width=1298
audio.mode=AM
