#HackRF Sweep saved settings
#Fri May 22 18:56:02 CEST 2026
SpurRemoval=false
Samples=8192
VideoFrameRate=15
WaterfallSpeed=4
GainLNA=40
SpectrumLineThickness=1
VideoFormat=GIF
FFTBinHz=200
GainVGA=12
AntennaPower=false
ShowPeaks=true
PersistentDisplayPersTime=5
FreqShift=0
InfoBoxVisible=true
GainTotal=52
paramFreqRange=758-788,791-821,1805-1880,2110-2170,2620-2690
Datestamp=true
SpectrumPaletteSize=65
LogDetail=SEC
ShowMaxHold=true
ShowAverage=false
VideoResolution=540
VideoArea=SPEC
AvgIterations=20
AvgOffset=0
WaterfallVisible=true
PersistentDisplay=false
SpectrumPaletteStart=-110
PowerFluxCal=50
AmplitudeOffset=-2
ShowPeakMarker=false
ShowHoldMarker=true
