#HackRF Sweep saved settings
#Fri May 22 19:13:46 CEST 2026
PeakMarkerCount=3
SpurRemoval=false
Samples=8192
VideoFrameRate=15
WaterfallSpeed=4
GainLNA=40
SpectrumLineThickness=1
VideoFormat=GIF
FFTBinHz=100
GainVGA=12
AntennaPower=false
ShowPeaks=true
HoldMarkerCount=1
PersistentDisplayPersTime=5
FreqShift=0
InfoBoxVisible=true
GainTotal=52
paramFreqRange=791-821,925-960
Datestamp=true
SpectrumPaletteSize=65
LogDetail=SEC
ShowMaxHold=true
ShowAverage=false
VideoResolution=540
VideoArea=SPEC
AvgIterations=20
AvgOffset=0
WaterfallVisible=true
PersistentDisplay=false
SpectrumPaletteStart=-110
PowerFluxCal=50
AmplitudeOffset=-3
ShowPeakMarker=false
ShowHoldMarker=false
