#HackRF Sweep saved settings
#Fri May 22 23:10:07 CEST 2026
SpurRemoval=false
Samples=8192
VideoFrameRate=15
WaterfallSpeed=4
GainLNA=40
SpectrumLineThickness=1
VideoFormat=GIF
FFTBinHz=100
GainVGA=12
AntennaPower=false
ShowPeaks=true
PersistentDisplayPersTime=5
RealTime=false
FreqShift=0
InfoBoxVisible=true
GainTotal=52
paramFreqRange=791-821,925-960
MarkerCount=2
Datestamp=true
SpectrumPaletteSize=65
LogDetail=SEC
ShowMaxHold=true
ShowAverage=false
VideoResolution=540
VideoArea=SPEC
AvgIterations=20
AvgOffset=0
WaterfallVisible=true
PersistentDisplay=false
SpectrumPaletteStart=-110
PowerFluxCal=50
AmplitudeOffset=-3
ShowPeakMarker=false
ShowHoldMarker=false
